### ISSUE TITLE
TimeLimitSec is Real but tm_lim is Int32

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/GLPK.jl#110]
The problem is that GLPK internally only accepts `Int32` as the time limit but `TimeLimitSec` supports Real values.

In general I'm unable to find a standard regarding the datatype that should be supported by `TimeLimitSec` Maybe @mlubin @odow know?

The TimeLimitSec function takes in `Real` values
https://github.com/JuliaOpt/GLPK.jl/blob/master/src/MOI_wrapper.jl#L293
but GLPK uses `Int32` for `tm_lim` such that setting it to a float doesn't work.

Additionally 
```
using GLPK
model = GLPK.Optimizer(tm_lim = 60.1)
```
doesn't work even though in the readme 

```
model = GLPK.Optimizer(tm_lim = 60.0)
```
looks like it would support floats as well.

I ran into the problem by setting `TimeLimitSec` inside Juniper to a floating point value.

I suggest to support `Union{Nothing,Real}` or `Union{Nothing,Float64}` as 
http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.TimeLimitSec mentions that it should be possible to set it to `nothing` as well.

and then GLPK should `floor` the value and convert it to `Int32` I suppose inside `TimeLimitSec`. I think:

```
model = GLPK.Optimizer(tm_lim = 60.1)
``` 
doesn't need to be supported but would change the readme to:
```
model = GLPK.Optimizer(tm_lim = 60)
```

Additionally we should mention in the MOI docs the type of the input for the set parameters if they are not clear.

If you agree I will create a PR here for the necessary changes.

**Comment by mlubin** [comment]
According to the GLPK documentation, `tm_lim` is the time limit in *milliseconds*. This isn't really an issue about `Real` vs `Float64`, just the implementation of `TimeLimitSec` being incorrect. It should also accept `nothing` to disable the time limit, as the MOI documentation suggests.

**Comment by Wikunia** [comment]
Ah okay thanks for clarifying that. The `60.0` in the readme look a lot like seconds 😂
Will make a PR later today.

**Comment by mlubin** [comment]
Yes, that's why we made sure to put the units in the name in MOI. :)

**Comment by Wikunia** [comment]
Is it possible to release a new version for it? Then Juniper get release it's MOI 0.9 / JuMP 0.20 version.
