### ISSUE TITLE
Error with ScalarAffineFunction-in-Interval constraint with equal bounds

### ISSUE THREAD

**Issue by pierre-haessig** [JuliaOpt/GLPK.jl#113]
Hello,
As a follow-up of this [JuMP discussion](https://discourse.julialang.org/t/jump-glpk-with-equal-upper-and-lower-bounds), I'm reporting a corner case issue with `ScalarAffineFunction-in-Interval` constraints, when the lower and upper bounds are equal. Here is a MWE:

```julia
using JuMP
using GLPK

model = Model(with_optimizer(GLPK.Optimizer))

@variable(model, x[1:2])
xmax = [10., 0.]
@constraint(model, 0. .<= x .<= xmax)
```
This is the output of the `@constraint` macro, with the two `ScalarAffineFunction-in-Interval` constraints:
```
2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.Interval{Float64}},ScalarShape},1}:
 x[1] ∈ [0.0, 10.0]
 x[2] ∈ [0.0, 0.0] 
```

Now, when solving the model,
```julia
@objective(model, Min, 0)
optimize!(model)
```
a GLPK error message is displayed (by the way, I'm not sure an actual Error is raised):
```
glp_simplex: row 2: lb = 0, ub = 0; incorrect bounds
```

As mentioned by @odow in the [discussion](https://discourse.julialang.org/t/jump-glpk-with-equal-upper-and-lower-bounds), there are workarounds (e.g.: splitting the interval constraint into two, or setting the bounds inside `@variable`), but if it were possible to have GLPK support this syntax like other solvers do (e.g. Clp), it would be nice.

Notice that there is a possibly related discussion on [GLPK mailing-list](https://lists.gnu.org/archive/html/help-glpk/2011-07/msg00088.html) “Can we set a row with equal upper and lower bound?”.

**Comment by odow** [comment]
This can be fixed by removing native support for ScalarAffineFunction-in-Interval constraints and using the bridges. This is what Gurobi does, for example.

**Comment by odow** [comment]
I've just realized that you were on 0.10 rather than 0.11. This is already fixed in the latest release of GLPK. (We don't support `ScalarAffineFunction-in-Interval` constraints.)

**Comment by pierre-haessig** [comment]
You're right. I've rerun my test example and it runs fine with `@constraint(model, 0. .<= x .<= xmax)`. Thanks!
