### ISSUE TITLE
How to know the elapse time using GLPK solver

### ISSUE THREAD

**Issue by lausilvag** [JuliaOpt/GLPK.jl#134]
Hi!
I am using the GLPK solver and in the output doesn’t appear the elapsed time:

GLPK Simplex Optimizer, v4.64
0: obj = 0.000000000e+000 inf = 3.846e+001 (1)
3: obj = 1.144956706e+007 inf = 0.000e+000 (0)

13: obj = 8.328774553e+006 inf = 0.000e+000 (0)
OPTIMAL LP SOLUTION FOUND
GLPK Integer Optimizer, v4.64
80 rows, 500 columns, 2810 non-zeros
500 integer variables, all of which are binary
Integer optimization begins…
13: mip = not found yet >= -inf (1; 0)
27: >>>>> 1.500585490e+008 >= 8.886042150e+006 94.1% (7; 0)
32: >>>>> 9.095841177e+007 >= 9.008360860e+006 90.1% (6; 1)
51: >>>>> 7.498068962e+007 >= 9.427087141e+006 87.4% (11; 3)
64: >>>>> 3.157159012e+007 >= 9.551510608e+006 69.7% (15; 4)
77: >>>>> 2.860642016e+007 >= 1.091156753e+007 61.9% (20; 8)
81: >>>>> 2.394664958e+007 >= 1.360769385e+007 43.2% (12; 16)
81: mip = 2.394664958e+007 >= tree is empty 0.0% (0; 55)
INTEGER OPTIMAL SOLUTION FOUND
Do you have any idea which command and/or parameter to use to make the elapse time appear?

I really really appreciate your help!

**Comment by odow** [comment]
Answered on discourse: https://discourse.julialang.org/t/how-to-know-the-elapse-time-using-glpk-solver/38511/2

GLPK supports the `SolveTime` attribute:
```julia
model = Model(GLPK.Optimizer)
optimize!(model)
@show solve_time(model)
```
