### ISSUE TITLE
How to set Cbc Parameters

### ISSUE THREAD

**Issue by lausilvag** [JuliaOpt/GLPK.jl#135]
Hi
I am trying to set parameters for Cbc Solver

Z_OP = Model(with_optimizer(Cbc.Optimizer))
    set_parameter(Z_OP, "preProcess", off)
    set_parameter(Z_OP, "CliqueCuts", Root)

UndefVarError: Off not defined
UndefVarError: Root not defined

Does anyone know how to fix the error and where I find updated information about the command to set new parameters?

Thank you! :)

Thank you

**Comment by odow** [comment]
Closing in favor of https://github.com/JuliaOpt/Cbc.jl/issues/135
