### ISSUE TITLE
Setting GLPK options

### ISSUE THREAD

**Issue by howard4086** [JuliaOpt/GLPK.jl#15]
I need a bit of help in setting GLPK's solver options.  Specifically I want to set the MIPGAP and the time limit.  I've tried the following, and it did not alter the solver behavior at all (ie - runs a long time and looks for the optimal solution).

m=Model(solver=GLPKSolverMIP())
params=GLPK.IntoptParam()
params.tm_lim=1
params.tol_obj=.5

#set up the model (omitted here)
status=solve(m)

Can someone tell me what I'm doing wrong?  Thanks.

**Comment by mlubin** [comment]
You can now set all GLPK options through the MathProgBase interface.
