### ISSUE TITLE
GLPK windows binary unavailable

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/GLPK.jl#25]
```
$ wget http://downloads.sourceforge.net/project/winglpk/winglpk/GLPK-4.52/winglpk-4.52.zip
--2015-07-24 19:43:42--  http://downloads.sourceforge.net/project/winglpk/winglpk/GLPK-4.52/winglpk-4.52.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-24 19:43:45 ERROR 404: Not Found.
```
Is this a temporary thing?
CC @tkelman

**Comment by tkelman** [comment]
Thought it might be that the url should be `projects/winglpk/files/winglpk`, but something is also messed up with sourceforge and I can't seem to download any files from that project through a browser either. I'll put a local copy up on bintray if I can find one.

**Comment by mlubin** [comment]
I can probably pull out a copy of the file from somewhere.

**Comment by tkelman** [comment]
found a copy, should be good enough - #26 worked so far on release win32, I can squash if needed
