### ISSUE TITLE
install error win 10, julia 4.2

### ISSUE THREAD

**Issue by kkmann** [JuliaOpt/GLPK.jl#30]
Pkg.add("GLPK")

error:

    ================================[ ERROR: GLPK ]=================================

    LoadError: No download agent available; install curl, wget, or fetch.
    while loading C:\Users\****\.julia\v0.4\GLPK\deps\build.jl, in expression starting on line 61

    ================================================================================

Do we really need to install curl manually?

**Comment by mlubin** [comment]
CC @tkelman

**Comment by tkelman** [comment]
No you shouldn't, BinDeps should be using powershell for this. What does ```success(`powershell -h`)``` return?

**Comment by tddaniel** [comment]
I am having a similar issue on windows 10 with Blosc
trying to Pkg.build("JLD")
gives
 LoadError: No download agent available; install curl, wget, or fetch.
while loading C:\Users\***\.julia\v0.4\Blosc\deps\build.jl, in expression starting on line 11

success(`powershell -h`) returns true

**Comment by tddaniel** [comment]
I had the exact same issue also on win10.  success(`powershell -h`) returns true.

**Comment by tkelman** [comment]
and `versioninfo(true)` ?

**Comment by tddaniel** [comment]
i get 

Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
           Microsoft Windows [Version 10.0.10586]
as well as an error 
`could not spawn ``uname -mpsrv``: no such file or directory (ENOENT)`

**Comment by tkelman** [comment]
ah right that's a bug in base julia that I need to fix. How about `Pkg.status()`

**Comment by tddaniel** [comment]
I get the following list.

10 required packages:
 - Blosc                         0.1.4+             master
 - GLPK                          0.2.17
 - Gadfly                        0.4.0              fcb24969 (dirty)
 - HDF5                          0.5.7
 - IJulia                        1.1.8
 - Jewel                         1.0.8
 - Nettle                        0.2.0+             master
 - ProgressMeter                 0.2.2
 - PyPlot                        2.1.1
 - WinRPM                        0.1.13


51 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - Colors                        0.6.0              83093643 (dirty)
 - Compat                        0.7.8              6de3fbaa (dirty)
 - Compose                       0.4.0              7861bc86 (dirty)
 - Conda                         0.1.8
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10             712e3876 (dirty)
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FactCheck                     0.4.2
 - FixedPointNumbers             0.1.1
 - GZip                          0.2.18
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - ImmutableArrays               0.0.11
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - JuliaParser                   0.6.3+             master (dirty)
 - KernelDensity                 0.1.2
 - LNR                           0.0.2
 - LaTeXStrings                  0.1.6
 - Lazy                          0.10.1
 - LibExpat                      0.1.0
 - Loess                         0.0.6
 - MacroTools                    0.2.0
 - Measures                      0.0.1
 - NaNMath                       0.1.1
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - PyCall                        1.2.0
 - Reexport                      0.0.3
 - Requires                      0.2.1
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4              cf943919 (dirty)
 - StatsFuns                     0.2.0
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - ZMQ                           0.3.1
 - Zlib                          0.1.12
 - tmply60fI                     0.0.0-             non-repo (unregistered)

**Comment by tkelman** [comment]
How about ```success(`powershell --help`)``` ? You may need to update to BinDeps 0.3.20.

**Comment by tddaniel** [comment]
That returned false. I will try updating BinDeps and see. Will report back. Thanks!

**Comment by tddaniel** [comment]
That seems to have fixed it. Thanks so much, that was bugging me all morning.

**Comment by tkelman** [comment]
No problem. I think we'll close this, @kkmann leave a comment if you still have trouble even with BinDeps 0.3.20 or newer.

**Comment by zhenzhenyan** [comment]
Hi, I am facing a similar problem when building mosek, I have update BinDeps but it still report the same issue. Can you help?

**Comment by zhenzhenyan** [comment]
But My Julia version is 0.4.6 now and the corresponding BinDeps is 0.4.2

**Comment by tkelman** [comment]
Wrong repository. If the problem occurs for Mosek.jl, open an issue there. Include full input and output, what you expected to happen vs what you saw, and the output of `versioninfo(true)`.

**Comment by zhenzhenyan** [comment]
oh.. sorry and thanks
