### ISSUE TITLE
Possible to link GLPK.jl to existing GLPK library

### ISSUE THREAD

**Issue by MikeRand** [JuliaOpt/GLPK.jl#48]
Hello,

I've downloaded and built GLPK 4.65 and would rather use this than the Julia-built 4.61 version. Is there a way to build GLPK.jl against my library rather than having it download and install a new one (e.g. by using push! to add the GLPK library path to DL_LOAD_PATH prior to running Pkg.build("GLPK"))?

Thanks,

Michael

**Comment by leethargo** [comment]
Similarly, I was surprised to see that the GLPK as installed by the Debian package `libglpk-dev` is not used when running `Pkg.build("GLPK")`.

**Comment by mlubin** [comment]
See https://github.com/JuliaOpt/GLPK.jl#custom-installation.
