### ISSUE TITLE
passing in parameters

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/GLPK.jl#49]
How does one pass in time limit, absolute optimality gap, and relative optimality gap stopping condition parameters to GPLK when using const solver = GLPKSolverMIP() ?

**Comment by leethargo** [comment]
I guess that this question applies to [GLPKMathProgInterface.jl](https://github.com/JuliaOpt/GLPKMathProgInterface.jl), where `GLPKSolverMIP` is defined?

**Comment by mlubin** [comment]
Yes, the readme at GLPKMathProgInterface says:

> Additionally, all low-level parameters which can be passed to the GLPK problem objects, such as msg_lev, tol_bnd etc., can also be passed as keyword arguments, for finer control. 

I.e., check the GLPK documentation and set the parameter as `GLPKSolverMIP(parameter_name=value)`.
