### ISSUE TITLE
Call glpk preprocessing on GLPK.jl

### ISSUE THREAD

**Issue by lrsantos11** [JuliaOpt/GLPK.jl#51]
GLPK 4.65 has a new API calling its preprocessor:
> GLPK 4.65 Release Information
>...
>      In this release:
>      The following new API routines for LP/MIP preprocessing were
>       added:

>        glp_npp_alloc_wksp    allocate the preprocessor workspace
>       glp_npp_load_prob     load original problem instance
>      glp_npp_preprocess1   perform basic LP/MIP preprocessing
>        glp_npp_build_prob    build resultant problem instance
>       glp_npp_postprocess   postprocess solution to resultant problem
>        glp_npp_obtain_sol    obtain solution to original problem
>       glp_npp_free_wksp     free the preprocessor workspace
>        See doc/npp.txt for detailed description of these API routines.

See more in <http://lists.gnu.org/archive/html/help-glpk/2018-02/msg00009.html>
 @mlubin: GLPK just released this feature we were talking last week.

Would be great if GLPK.jl could make this routines available easily.

**Comment by lrsantos11** [comment]
Any news on that guys? Can I help and make a PR?

**Comment by mlubin** [comment]
I'm not aware of any plans to wrap this API. The first step would be to update the wrapper to support GLPK 4.65. This may be as easy as changing this line:
https://github.com/JuliaOpt/GLPK.jl/blob/0da1a7953aee25d51b93270413c990bd5e5d2ebb/deps/verreq.jl#L4

But we need to make sure it's properly tested and that there haven't been any breaking API changes between 4.62 and 4.65.
