### ISSUE TITLE
Build failing on Ubuntu 18.04.1 even after installing libgmp-dev

### ISSUE THREAD

**Issue by aritrasep** [JuliaOpt/GLPK.jl#60]
│ ERROR: LoadError: failed process: Process(setenv(`/home/aritra/.julia/packages/GLPK/thMVo/deps/src/glpk-4.61/configure --with-gmp --prefix=/home/aritra/.julia/packages/GLPK/thMVo/deps/usr`,

**Comment by mlubin** [comment]
It looks like this was trying to use GLPK on Julia 0.7 before it was supported. Please try again and open an new issue if needed.
