### ISSUE TITLE
Build fails on Julia 1.0 on MacOS

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaOpt/GLPK.jl#62]
Building GLPK ───→ `~/.julia/packages/GLPK/thMVo/deps/build.log`
┌ Error: Error building `GLPK`: 
│ ERROR: LoadError: MethodError: no method matching replace(::String, ::String, ::String)
│ Closest candidates are:
│   replace(::String, !Matched::Pair{#s55,B} where B where #s55<:AbstractChar; count) at strings/util.jl:414
│   replace(::String, !Matched::Pair{#s52,B} where B where #s52<:Union{Tuple{Vararg{AbstractChar,N} where N}, Set{#s49} where #s49<:AbstractChar, AbstractArray{#s50,1} where #s50<:AbstractChar}; count) at strings/util.jl:419
│   replace(::String, !Matched::Pair; count) at strings/util.jl:423
│   ...
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/arora/.julia/packages/GLPK/thMVo/deps/build.jl:10
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by odow** [comment]
Glpk.jl has not been updated to Julia 1.0. PRs accepted :)
