### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by asavasci** [JuliaOpt/GLPK.jl#96]
I am not able to resolve this build error, any help will be appreciated.
```julia
(v1.0) pkg> build GLPK
  Building GLPK → `~/.julia/packages/GLPK/rw631/deps/build.log`
┌ Error: Error building `GLPK`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaMath/GMPBuilder/releases/download/v6.1.2-2/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz to /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/usr/downloads/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz...
│ ERROR: LoadError: LoadError: Could not download https://github.com/JuliaMath/GMPBuilder/releases/download/v6.1.2-2/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz to /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/usr/downloads/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #download#89(::Bool, ::Function, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:498
│  [3] #download at ./none:0 [inlined]
│  [4] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:567
│  [5] #download_verify at ./none:0 [inlined]
│  [6] #install#129(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [8] top-level scope at /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/build_GMP.v6.1.2.jl:36
│  [9] include at ./boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at ./loading.jl:1044
│  [11] include at ./sysimg.jl:29 [inlined]
│  [12] include(::String) at ./loading.jl:1079
│  [13] top-level scope at none:0
│  [14] eval at ./boot.jl:319 [inlined]
│  [15] evalfile(::String, ::Array{String,1}) at ./loading.jl:1075 (repeats 2 times)
│  [16] top-level scope at /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/build.jl:37
│  [17] include at ./boot.jl:317 [inlined]
│  [18] include_relative(::Module, ::String) at ./loading.jl:1044
│  [19] include(::Module, ::String) at ./sysimg.jl:29
│  [20] include(::String) at ./client.jl:392
│  [21] top-level scope at none:0
│ in expression starting at /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/build_GMP.v6.1.2.jl:32
│ in expression starting at /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/build.jl:31
│ [19:37:41] dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ [19:37:41]   Referenced from: /anaconda3/lib/libssh2.1.dylib
│ [19:37:41]   Reason: image not found
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

**Comment by blegat** [comment]
There url https://github.com/JuliaMath/GMPBuilder/releases/download/v6.1.2-2/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz seems to work. Have you got an internet connection issue ?
What happens if you do
```
$ wget -O /Users/alpersavasci/.julia/packages/GLPK/rw631/deps/usr/downloads/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz https://github.com/JuliaMath/GMPBuilder/releases/download/v6.1.2-2/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz

**Comment by asavasci** [comment]
I am getting 
-bash: wget: command not found

**Comment by odow** [comment]
Try installing Ipopt:
```julia
] add Ipopt
```

It looks like a network issue though, so just re-try `] add GLPK`?

**Comment by asavasci** [comment]
Ipopt could not been built

Building Ipopt → `~/.julia/packages/Ipopt/Iu7vT/deps/build.log`
┌ Error: Error building `Ipopt`: 
│ [ Info: Downloading https://github.com/JuliaOpt/IpoptBuilder/releases/download/v3.12.10-1-static-1/IpoptBuilder.v3.12.10.x86_64-apple-darwin14-gcc7.tar.gz to /Users/alpersavasci/.julia/packages/Ipopt/Iu7vT/deps/usr/downloads/IpoptBuilder.v3.12.10.x86_64-apple-darwin14-gcc7.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaOpt/IpoptBuilder/releases/download/v3.12.10-1-static-1/IpoptBuilder.v3.12.10.x86_64-apple-darwin14-gcc7.tar.gz to /Users/alpersavasci/.julia/packages/Ipopt/Iu7vT/deps/usr/downloads/IpoptBuilder.v3.12.10.x86_64-apple-darwin14-gcc7.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #download#89(::Bool, ::Function, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:498
│  [3] #download at ./none:0 [inlined]
│  [4] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:567
│  [5] #download_verify at ./none:0 [inlined]
│  [6] #install#129(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /Users/alpersavasci/.julia/packages/BinaryProvider/4F5Hq/src/Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [8] top-level scope at /Users/alpersavasci/.julia/packages/Ipopt/Iu7vT/deps/build.jl:84
│  [9] include at ./boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at ./loading.jl:1044
│  [11] include(::Module, ::String) at ./sysimg.jl:29
│  [12] include(::String) at ./client.jl:392
│  [13] top-level scope at none:0
│ in expression starting at /Users/alpersavasci/.julia/packages/Ipopt/Iu7vT/deps/build.jl:67
│ [15:30:11] dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ [15:30:11]   Referenced from: /anaconda3/lib/libssh2.1.dylib
│ [15:30:11]   Reason: image not found
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

**Comment by odow** [comment]
This is a network error. (I see also https://github.com/JuliaWeb/MbedTLS.jl/issues/201.)

You should check with your IT about firewall settings etc. This isn't an issue with GLPK.jl.

**Comment by asavasci** [comment]
after updating anaconda it is resolved

**Comment by odow** [comment]
Glad you got it sorted.
